site_name: SEEREP Documentation
repo_url: https://github.com/agri-gaia/seerep
docs_dir: docs/mkdocs
# define navigation structure
nav:
  - Home: 'home/index.md'
  - Getting started:
    - Client:
      - gRPC python: 'getting-started/client/pypi.md'
    - Server:
      - Configuration: 'getting-started/server/configuration.md'
      - Dev Environment: 'getting-started/server/installationDev.md'
      - Kubernetes Deployment: 'getting-started/server/kubernetes-deployment.md'
      - Local Deployment: 'getting-started/server/local-deployment.md'
      - Docs: 'getting-started/server/docs.md'
      - Tests: 'getting-started/server/tests.md'
  - Reference:
    - Package Overview: 'reference/packages.md'
    - Python helper functionality: 'reference/python-helpers.md'
    - Python tests message abstractions: 'reference/pytests-message-abstractions.md'
  - Tutorials:
    - Overview: 'tutorials/overview.md'
    - Creating & retrieving projects: 'tutorials/projects.md'
    - Sending & querying images: 'tutorials/images.md'
    - Writing python examples: 'tutorials/writing-python-examples.md'
    - Writing python integration tests: 'tutorials/writing-python-tests.md'
theme:
  # use mkdocs material https://squidfunk.github.io/mkdocs-material/
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  # dark mode toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # navigation features
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.sections
  # disable google fonts due to GDPR
  font: false
# dfki color theme
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - privacy
markdown_extensions:
  # aka call-outs, way to include side content
  - admonition
  # syntax highlighting in code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  # allow references to code blocks for more direct examples
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  # add tabs to navigate on the top
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
copyright: Copyright &copy; 2021 - 2024 Deutsches Forschungszentrum für Künstliche Intelligenz GmbH (DFKI) <br>
  <a href="/seerep/mkdocs/legal-notice/index.html">Legal Notice</a> - <a href="/seerep/mkdocs/data-protection-notice/index.html">Data Protection Notice</a>
