site_name: SEEREP Documentation
site_description: Documentation for the SEemantic Environment REpresentation (SEEREP)
site_author: Mark Niemeyer, Julian Arkenau, Marc Meijer

repo_url: https://github.com/DFKI-NI/seerep
repo_name: DFKI-NI/seerep
edit_uri: edit/main/docs/mkdocs

docs_dir: docs/mkdocs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tabs
    - content.action.edit
    - search.suggest
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  logo: imgs/Seerep_Logo_White.svg
  favicon: imgs/Seerep_Favicon.png
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  # allow references to code blocks for more direct examples
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: 'home/index.md'
  - Getting started:
    - Development Setup: 'getting-started/dev_setup.md'
    - Server Deployment: 'getting-started/server_deployment.md'
    - gRPC Clients: 'getting-started/grpc_clients.md'
    - Documentation Setup: 'getting-started/docs.md'
    - Test Setup: 'getting-started/tests.md'
    - Kown Issues: 'getting-started/known_issues.md'
  - Reference:
    - gRPC API: reference/api.md
    - Package Overview: 'reference/packages.md'
    - Flatbuffers Abstractions: 'reference/pytests-message-abstractions.md'
    - Python Helpers: 'reference/python-helpers.md'
  - Tutorials:
    - Overview: 'tutorials/overview.md'
    - Creating & retrieving projects: 'tutorials/projects.md'
    - Sending & Querying Images: 'tutorials/images.md'
    - Writing Python Tests: 'tutorials/writing-python-tests.md'
    - Writing Python Examples: 'tutorials/writing-python-examples.md'

copyright: Copyright &copy; 2021 - 2024 Deutsches Forschungszentrum für Künstliche Intelligenz GmbH (DFKI) <br>
  <a href="/seerep/mkdocs/legal-notice/index.html">Legal Notice</a> - <a href="/seerep/mkdocs/data-protection-notice/index.html">Data Protection Notice</a>

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - privacy
  - glightbox
