site_name: SEEREP Documentation
site_description: Documentation for the SEemantic Environment REpresentation (SEEREP)
site_author: Mark Niemeyer, Julian Arkenau, Marc Meijer

repo_url: https://github.com/agri-gaia/seerep
repo_name: agri-gaia/seerep
edit_uri: edit/main/docs/mkdocs

docs_dir: docs/mkdocs
theme:
  name: material
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tabs
    - content.action.edit
    - search.suggest
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  favicon: imgs/DFKI-Logo_ohne_RGB_weiss.svg
  logo: imgs/Seerep_Logo_White.svg
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  # allow references to code blocks for more direct examples
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: 'home/index.md'
  - Getting started:
    - Client:
      - gRPC python: 'getting-started/client/pypi.md'
    - Server:
      - Configuration: 'getting-started/server/configuration.md'
      - Dev Environment: 'getting-started/server/installationDev.md'
      - Kubernetes Deployment: 'getting-started/server/kubernetes-deployment.md'
      - Local Deployment: 'getting-started/server/local-deployment.md'
      - Docs: 'getting-started/server/docs.md'
      - Tests: 'getting-started/server/tests.md'
  - Reference:
    - Package Overview: 'reference/packages.md'
  - Tutorials:
    - Overview: 'tutorials/overview.md'
    - gRPC Python: 'tutorials/overview.md'
    - Creating & retrieving projects: 'tutorials/projects.md'
    - Sending & Querying Images: 'tutorials/images.md'

copyright: Copyright &copy; 2021 - 2024 Deutsches Forschungszentrum für Künstliche Intelligenz GmbH (DFKI) <br>
  <a href="/seerep/mkdocs/legal-notice/index.html">Legal Notice</a> - <a href="/seerep/mkdocs/data-protection-notice/index.html">Data Protection Notice</a>

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - privacy
  - glightbox
