version: "3.6"
services:
  seerep:
    image: ghcr.io/agri-gaia/seerep_server:latest
    tty: true
    container_name: seerep_server
    command:
      # define data-dir for seerep-server
      - "--data-folder=/mnt/seerep-data"
    ports:
      # the gRPC port
      - 9090:9090
    volumes:
      # persist the data folder
      - seerep-data:/mnt/seerep-data #using docker volume
      #- /your/local/absolute/path:/mnt/seerep-data #using host folder
    environment:
      - TZ=Europe/Berlin
volumes:
  seerep-data:
