name: Build Docker from scratch unconditionally

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker:
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: git.ni.dfki.de:5050/agrigaia/seerep
          username: ${{ secrets.GITLAB_REGISTRY_USER }}
          password: ${{ secrets.GITLAB_REGISTRY_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/base/Dockerfile
          tags: git.ni.dfki.de:5050/agrigaia/seerep/base:latest
          cache-from: type=registry,ref=git.ni.dfki.de:5050/agrigaia/seerep/base:latest
          cache-to: type=inline
      -
        name: Build and push dev image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/dev/Dockerfile
          tags: git.ni.dfki.de:5050/agrigaia/seerep/dev:latest
          cache-from: type=registry,ref=git.ni.dfki.de:5050/agrigaia/seerep/dev:latest
          cache-to: type=inline
      -
        name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: docker/server/Dockerfile
          tags: git.ni.dfki.de:5050/agrigaia/seerep/server:latest
          cache-from: type=registry,ref=git.ni.dfki.de:5050/agrigaia/seerep/server:latest
          cache-to: type=inline
