name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, feature/devcontainer ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docker:
    # run on ubuntu
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      # get the list of changed file
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v8.1
      # only build the image if the Dockerfile or the Dependencies changed
      - name: Build the latest Docker image
        if: |
          contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'installDependencies.sh')
        run: docker build . --file Dockerfile --tag seerep/dev-image:latest
      #login if on master and image was build
      - name: Login to DockerHub Registry
        if: |
          ( contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'installDependencies.sh') ) &&
          GitHub.event_name != 'pull_request'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      # push image if on master and image was build
      - name: Push the latest Docker image
        if: |
          ( contains(steps.changed-files.outputs.modified_files, 'Dockerfile') ||
          contains(steps.changed-files.outputs.modified_files, 'installDependencies.sh') ) &&
          GitHub.event_name != 'pull_request'
        run: docker push seerep/dev-image:latest

  # This workflow contains a single job called "build"
  build:
    needs: build-docker
    # run in docker container on ubuntu
    runs-on: ubuntu-20.04
    container:
      image: seerep/dev-image:latest
      options: --user docker --workdir /home/docker

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Move the code in a "src" folder for catkin build
      - name: Move code to src folder
        run: |
          shopt -s dotglob
          mkdir $GITHUB_WORKSPACE/../tmp
          mv $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/../tmp/
          mkdir -p $GITHUB_WORKSPACE/src/seerep
          mv $GITHUB_WORKSPACE/../tmp/* $GITHUB_WORKSPACE/src/seerep/
        shell: bash

      #build workspace
      - name: Build the ros workspace
        run: |
          source /opt/ros/noetic/setup.bash
          catkin build --workspace $GITHUB_WORKSPACE/
        shell: bash

      #pre-commit checks
      - name: run pre-commit tests
        run: |
          source /opt/ros/noetic/setup.bash
          source $GITHUB_WORKSPACE/devel/setup.bash
          cd $GITHUB_WORKSPACE/src/seerep; pwd; ls -alFh ; pre-commit run -a
        shell: bash
