name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - feature/add_github_action
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # run in docker container on ubuntu
    runs-on: ubuntu-latest
    container:
      image: seerep/dev-image:latest
      options: --user 1001

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Move the code in a "src" folder for catkin build
      - name: Move code to src folder
        run: mv $GITHUB_WORKSPACE $GITHUB_WORKSPACE/../src

      # build workspace
      - name: Build the ros workspace
        run: catkin build --workspace $GITHUB_WORKSPACE/..
