name: Tests

on:
  push:

jobs:
  hdf5-interface:
    name: HDF5 Interface
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agri-gaia/seerep_base:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: src
    - name: Build seerep_hdf5 packages
      run: |
        source /opt/ros/noetic/setup.bash
        catkin build seerep_hdf5_* --workspace $GITHUB_WORKSPACE/
        source $GITHUB_WORKSPACE/devel/setup.bash
      shell: bash
    - name: Run flatbuffer tests
      run: catkin test seerep_hdf5_fb
      shell: bash
    - name: Run protobuf tests
      run: catkin test seerep_hdf5_pb
      shell: bash

  ros-converions:
    name: ROS Conversions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/agri-gaia/seerep_base:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: src
    - name: Build seerep_ros packages
      run: |
        source /opt/ros/noetic/setup.bash
        catkin build seerep_ros_* --workspace $GITHUB_WORKSPACE/
        source $GITHUB_WORKSPACE/devel/setup.bash
      shell: bash
    - name: Test flatbuffer conversions
      run: catkin test seerep_ros_conversions_fb
      shell: bash
